#[path = "common/command_contract_sets.rs"]
mod command_contract_sets;
#[path = "common/switching.rs"]
mod switching;

use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

use command_contract_sets::{
    acl_manifest_commands, autogenerated_permission_commands, build_manifest_commands,
    exact_set_mismatch, exact_string_set_mismatch, load_capability_config,
    load_permission_manifest, load_tauri_config, permission_commands, runtime_commands,
    schema_commands, BACKEND_COMMANDS, PERMISSION_COMMANDS, QUICK_SWITCH_COMMANDS,
    QUICK_SWITCH_PERMISSION_IDENTIFIERS, SETTINGS_COMMANDS, SETTINGS_PERMISSION_IDENTIFIERS,
};
use omo_switch_tauri::application::{ApplicationError, GroupApplicationService};
use omo_switch_tauri::commands::AppStateResponse;
use omo_switch_tauri::core::models::ModelGroup;
use omo_switch_tauri::core::switching::SwitchError;
use switching::{
    category_row, group, override_row, paths, remove_temp, seed_groups, seed_opencode, seed_state,
    temp_home,
};

#[test]
fn commands_when_saving_duplicate_name_returns_stable_error() {
    let home = temp_home("commands-duplicate-name");
    let first = dual_target_group();
    let second = group(
        "55555555-5555-4555-8555-555555555555",
        "Second",
        true,
        Vec::new(),
        Vec::new(),
        Vec::new(),
    );
    seed_groups(&home, &[first.clone(), second.clone()]);
    seed_state(&home, None, None);
    let service = GroupApplicationService::for_home(&home).expect("Given: fake HOME resolves");
    let mut duplicate = second;
    duplicate.name = first.name;

    let error = service
        .save_group(duplicate)
        .expect_err("When: duplicate group name is saved");

    assert!(matches!(error, ApplicationError::DuplicateGroupName));
    remove_temp(&home);
}

#[test]
fn commands_when_active_group_save_reapply_fails_returns_transaction_error() {
    let home = temp_home("commands-active-save-reapply");
    let target = dual_target_group();
    seed_groups(&home, &[target.clone()]);
    seed_state(&home, Some(target.id), Some(&target.name));
    seed_opencode(&home);
    let target_paths = paths(&home);
    fs::create_dir_all(target_paths.opencode_dir()).expect("Given: target directory exists");
    fs::write(target_paths.oh_my_openagent_file(), "{ malformed: ")
        .expect("Given: active target is malformed");
    let service = GroupApplicationService::for_home(&home).expect("Given: fake HOME resolves");
    let mut edited = target;
    edited.description = Some("Requires active reapply".to_owned());

    let error = service
        .save_group(edited)
        .expect_err("When: active group save attempts transactional reapply");

    assert!(matches!(
        error,
        ApplicationError::Switch(SwitchError::LoadOhMyConfigFailed)
    ));
    remove_temp(&home);
}

#[test]
fn commands_when_serializing_app_state_does_not_expose_backend_paths() {
    let home = temp_home("commands-owned-dto");
    seed_groups(&home, &[]);
    seed_state(&home, None, None);
    let service = GroupApplicationService::for_home(&home).expect("Given: fake HOME resolves");

    let state = service
        .load_app_state()
        .expect("When: app state loads through application service");
    let serialized = serde_json::to_value(AppStateResponse {
        groups: state.groups,
        app_state: state.app_state,
        discovered_open_code_agent_names: state.discovered_open_code_agent_names,
        open_code_agent_discovery_error: state.open_code_agent_discovery_error,
    })
    .expect("Then: command response serializes");

    assert!(serialized.get("paths").is_none());
    remove_temp(&home);
}

#[test]
fn commands_registration_surfaces_match_approved_command_sets() {
    let surfaces = [
        (
            "runtime handler",
            runtime_commands(include_str!("../src/lib.rs")),
            BACKEND_COMMANDS,
        ),
        (
            "build manifest",
            build_manifest_commands(include_str!("../build.rs")),
            BACKEND_COMMANDS,
        ),
        (
            "permissions",
            permission_commands(include_str!("../permissions/group-commands.toml")),
            PERMISSION_COMMANDS,
        ),
        (
            "desktop generated schema",
            schema_commands(include_str!("../gen/schemas/desktop-schema.json")),
            BACKEND_COMMANDS,
        ),
        (
            "windows generated schema",
            schema_commands(include_str!("../gen/schemas/windows-schema.json")),
            BACKEND_COMMANDS,
        ),
        (
            "generated ACL manifest",
            acl_manifest_commands(include_str!("../gen/schemas/acl-manifests.json")),
            BACKEND_COMMANDS,
        ),
        (
            "autogenerated permissions",
            autogenerated_permission_commands(
                std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                    .join("permissions/autogenerated")
                    .as_path(),
            ),
            BACKEND_COMMANDS,
        ),
    ];

    for (surface, actual, expected) in surfaces {
        if let Some(mismatch) = exact_set_mismatch(surface, &actual, expected) {
            panic!("{mismatch}");
        }
    }
}

#[test]
fn commands_exact_contract_rejects_unknown_and_missing_names() {
    let actual = vec![
        "load_app_state".to_owned(),
        "injected_unknown_command".to_owned(),
    ];

    let mismatch = exact_set_mismatch(
        "mutation probe",
        &actual,
        &["load_app_state", "switch_group"],
    )
    .expect("Then: an injected unknown command cannot produce a success result");

    assert!(mismatch.contains("missing=[\"switch_group\"]"));
    assert!(mismatch.contains("unexpected=[\"injected_unknown_command\"]"));
}

#[test]
fn commands_generated_contract_rejects_stale_permission_and_schema_names() {
    let stale_permission = permission_commands(
        r#"
[[permission]]
identifier = "mutation-probe"
commands.allow = ["load_app_state", "injected_unknown_command"]
"#,
    );
    let stale_schema = schema_commands(
        r#"{"const":"allow-injected-unknown-command","description":"Enables the injected_unknown_command command without any pre-configured scope."}"#,
    );

    assert!(
        exact_set_mismatch("permission probe", &stale_permission, &["load_app_state"]).is_some()
    );
    assert!(exact_set_mismatch("schema probe", &stale_schema, &[]).is_some());
}

#[test]
fn commands_window_capabilities_enforce_exact_least_privilege_contracts() {
    let tauri_root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let tauri_config = load_tauri_config(&tauri_root.join("tauri.conf.json"));
    let permissions = load_permission_manifest(&tauri_root.join("permissions/group-commands.toml"));
    let quick_switch = load_capability_config(&tauri_root.join("capabilities/quick-switch.json"));
    let settings = load_capability_config(&tauri_root.join("capabilities/settings.json"));

    assert_eq!(
        tauri_config
            .app
            .windows
            .iter()
            .map(|window| window.label.as_str())
            .collect::<Vec<_>>(),
        ["quick-switch", "settings"],
        "tauri.conf.json must configure exactly the quick-switch and settings window labels"
    );
    assert_eq!(
        tauri_config.app.security.capabilities,
        ["quick-switch", "settings"],
        "tauri.conf.json must activate exactly the two window capabilities"
    );

    assert_eq!(quick_switch.identifier, "quick-switch");
    assert!(quick_switch.local);
    assert_eq!(quick_switch.windows, ["quick-switch"]);
    assert_eq!(
        quick_switch.permissions, QUICK_SWITCH_PERMISSION_IDENTIFIERS,
        "quick-switch capability permission references changed"
    );
    let quick_switch_commands = quick_switch
        .allowed_commands(&permissions)
        .expect("Given: quick-switch capability resolves all of its permissions");
    assert_exact_command_set(
        "quick-switch public command set",
        &quick_switch_commands,
        QUICK_SWITCH_COMMANDS,
    );
    assert_eq!(
        quick_switch_commands.len(),
        2,
        "quick-switch must own exactly two public commands"
    );

    assert_eq!(settings.identifier, "settings");
    assert!(settings.local);
    assert_eq!(settings.windows, ["settings"]);
    assert_eq!(
        settings.permissions, SETTINGS_PERMISSION_IDENTIFIERS,
        "settings capability permission combination changed"
    );
    let settings_commands = settings
        .allowed_commands(&permissions)
        .expect("Given: settings capability resolves all of its permissions");
    assert_exact_command_set(
        "settings public command set",
        &settings_commands,
        SETTINGS_COMMANDS,
    );
    assert_eq!(
        settings_commands.len(),
        6,
        "settings must own exactly six public commands"
    );

    for command in settings_commands.difference(&quick_switch_commands) {
        let error = quick_switch
            .authorize_command(&permissions, command)
            .expect_err("When: a settings-only command is requested from quick-switch");
        assert!(
            error.contains("quick-switch") && error.contains(command),
            "authorization failure must identify the quick-switch capability and denied command: {error}"
        );
    }
}

fn assert_exact_command_set(subject: &str, actual: &BTreeSet<String>, expected: &[&str]) {
    let expected = expected
        .iter()
        .map(|command| (*command).to_owned())
        .collect::<BTreeSet<_>>();
    if let Some(mismatch) = exact_string_set_mismatch(subject, actual, &expected) {
        panic!("{mismatch}");
    }
}

fn dual_target_group() -> ModelGroup {
    group(
        "44444444-4444-4444-8444-444444444444",
        "Dual Target",
        true,
        vec![category_row(
            "unspecified-high",
            "cliproxyapi/gpt-5.4-xhigh",
        )],
        Vec::new(),
        vec![
            override_row("creative-ui-coder", "cliproxyapi/gpt-5.4"),
            override_row("Jenny", "cliproxyapi/gpt-5.4-xhigh"),
        ],
    )
}
